### ISSUE TITLE
GLMMadaptive models

### ISSUE THREAD

**Issue by strengejacke** [easystats/circus#4]
```r
library("GLMMadaptive")
library("lme4")

data(cbpp)

fish <- read.csv("https://stats.idre.ucla.edu/stat/data/fish.csv")
fish$nofish <- as.factor(fish$nofish)
fish$livebait <- as.factor(fish$livebait)
fish$camper <- as.factor(fish$camper)

GLMMadaptive_zi_1 <- GLMMadaptive::mixed_model(
  count ~ child + camper,
  random = ~ 1 | persons,
  zi_fixed = ~ child + livebait,
  data = fish,
  family = GLMMadaptive::zi.poisson()
)

GLMMadaptive_zi_2 <- GLMMadaptive::mixed_model(
  count ~ child + camper,
  random = ~ 1 | persons,
  zi_fixed = ~ child + livebait,
  zi_random = ~ 1 | persons,
  data = fish,
  family = GLMMadaptive::zi.poisson()
)

GLMMadaptive_1 <- GLMMadaptive::mixed_model(
  cbind(incidence, size - incidence) ~ period,
  random = ~ 1 | herd,
  data = cbpp,
  family = binomial
)
```

**Comment by DominiqueMakowski** [comment]
I've added the models, as well as some info with steps on how to add models #3 Let me ~think~ **know** if it's clear enough :)

**Comment by strengejacke** [comment]
Ok, got it! Is there a reason why you commented out the new models in the readme?

**Comment by DominiqueMakowski** [comment]
yes, because I could not manage to knit them... it said pandoc error something something, but it might be related to my version of pandoc

**Comment by strengejacke** [comment]
I'm still not used to having 2 readme files ;-) For insight, I removed readme.rmd, because it caused troubles when submitting to CRAN...

**Comment by DominiqueMakowski** [comment]
Hum, I think it's becoming a standard procedure, maybe we have to add it to the rbuildignore to avoid packaging it along when submitting to CRAN?

**Comment by strengejacke** [comment]
You can check and get some experience when submitting bayestestR ;-)
