### ISSUE TITLE
More simple (fast) way to add a single model?

### ISSUE THREAD

**Issue by mattansb** [easystats/circus#6]
It is my understanding that to add a single model, it is required to re-fit *all* the models. 

> 3. Run all the chunks manually: this will create the models, and then the use_data() function will save them inside the package’s data folder

As more and more models are added to `circus` this will become more time consuming.
Is there any way to simplify this process?

**Comment by DominiqueMakowski** [comment]
Yes it is currently time-consuming indeed...

I guess manually running a new chunk of models, then adding them by running use_data() on the subset of new models should work. Maybe we should run the use_data() at the end of each chunk of models, so that we can run and update them independently?

**Comment by strengejacke** [comment]
> It is my understanding that to add a single model, it is required to re-fit all the models.

No. 

1) Simply fit your model, and use `usethis::use_data(mymodel)`
2) If possible, at the code to fit the model to `data.R`, the documentation
3) Add the code also to the `Readme.rmd` _and_ your model name to the usethis-code at the bottom of the readme.
4) then _knit_ the Readme-rmd-file. As all chunks are set to `eval = FALSE`, no chunk is evaluated, so you quickly get the Readme.md
5) build docs, so your changes in `data.R` are also updated in `data.rd`
6) commit: 
  - your model (in `/data/mymodel.rda`),
  - `data.R`
  - `data.rd`
  - `Readme.rmd`
  - `Readme.md`

It's a thing of a few minutes.

**Comment by strengejacke** [comment]
I updated the readme...
